---
# kubernetes master nodes
- hosts: 10.68.0.11
  vars:
    ansible_python_interpreter: "/home/core/bin/python"
    ansible_become: true
  gather_facts: True
  roles:
  - k8s-master

# kubernetes worker nodes
- hosts: 10.68.2.11
  vars:
    ansible_python_interpreter: "/home/core/bin/python"
    ansible_become: true
  gather_facts: True
  roles:
  - k8s-worker
