---
- name: Create /etc/kubernets/manifests
  file:
    path: /etc/kubernetes/{{item}}
    state: directory
    recurse: yes
  with_items: [ "manifests", "ssl", "cni" ]

  #- name: Create directories /etc/kubernetes/manifests
  #$file: 
  # path: /etc/kubernetes/{{item}} 
  #  state: directory 
  #  mode: 0755 
  #  recurse: no
  #  owner: root 
  #  group: root
  #with_items: [ "manifests", "ssl", "cni" ]

- name: Kubelet systemd service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    mode: 0644
  tags: kubelet

- name: Write Kubernetes Manifests
  template:
    src: "{{ item }}.yaml.j2"
    dest: /etc/kubernetes/manifests/{{item}}.yaml
    mode: 0644
  with_items: [ "kube-apiserver", "kube-proxy", "kube-controller-manager", "kube-scheduler" ]
  tags: kubernetes-manifest
