---
etcd_endpoints: &etcd_endpoints "http://{{ ansible_local.k8s_facts.etcd_servers | default('localhost') }}:2379"

# locksmithd etcd servers used for coordination
locksmithd_etcd_endpoints: *etcd_endpoints

# locksmithd control group
locksmithd_control_group: "{{ ansible_local.k8s_facts.labels.role | default('') }}"

